services:
  apollo-sever:
    image: node:16.17.1
    command: sh -c "npm install && npm run start"
    ports:
      - "4002:4002"
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true